### ISSUE TITLE
ApiError

### ISSUE THREAD

**Issue by Rushika-Parikh** [Furry/2captcha#11]
I got this error recently and I don't know what it means and how to solve it or avoid it

APIError: An Unexpected Error has occured. Please submit an issue on GitHub detailing this event.
    at Solver.recaptcha (/Users/rushika/node_modules/2captcha/dist/structs/2captcha.js:149:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  err: 'Not Found',
  name: 'APIError',
  code: 0
}

**Comment by Furry** [comment]
Hiya! Thank you for submitting the issue. Could you please show me your current code, with any sensitive information (IE 2captcha token) removed?

If not, what type of captcha were you attempting to solve, and did you have any special properties passed to the function?

**Comment by Rushika-Parikh** [comment]
const Captcha = require("2captcha");
const solver = new Captcha.Solver("API_KEY");
solver.recaptcha("DATA_SITE_KEY", "SITE_NAME")
.then((res) => {
	console.log(res);
}).catch(function(error){
	console.log("ERROR FOUND");
	console.log(error);
});

I was trying to solve recaptcha v3

**Comment by Furry** [comment]
I'm unsure what might have caused this error. For now, I'm going to close the issue, as it seems to be related with 2captcha itself. (The "Not Found" error code isn't in their documentation, therefor I don't handle it through my library). In the future if I find a solution to this, or it starts to come up more often, I will reopen the issue and investigate further.
