### ISSUE TITLE
CAPCHA_NOT_READY

### ISSUE THREAD

**Issue by matheusbento** [Furry/2captcha#13]
Hi guys, I was testing 2captcha API and it returns this error for the first time:

```
APIError: An Unexpected Error has occured. Please submit an issue on GitHub detailing this event.
    at Solver.pollResponse (....\node_modules\2captcha\dist\structs\2captcha.js:106:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  err: 'CAPCHA_NOT_READY',
  name: 'APIError',
  code: 0
}
```

Anyone knows why this happen?

**Comment by Furry** [comment]
Hiya! Could you please share the code that caused this issue?

**Comment by matheusbento** [comment]
```
const Captcha = require("2captcha");
const solver = new Captcha.Solver(process.env.TWOCAPTCHA_API_KEY);
const result = await solver.imageCaptcha(image);
console.log(result);
resolve(result.data);
```

This is the code i'm using right now.

**Comment by Oliver5906** [comment]
> I believe I fixed this issue in an earlier version, I had a case miss-typed within the library.. If this issue persists please let me know.

Can you tell me the solution please?

**Comment by Furry** [comment]
> > I believe I fixed this issue in an earlier version, I had a case miss-typed within the library.. If this issue persists please let me know.
> 
> Can you tell me the solution please?

Are you getting the exact same error as above @Oliver5906?
