### ISSUE TITLE
[feature request] Support for instructions on image CAPTCHAs

### ISSUE THREAD

**Issue by tacohitbox** [Furry/2captcha#21]
This is for sites like Filecrypt.cc that has different CAPTCHAs for each. Would be helpful to have, as well as supporting coordinates.

**Comment by Furry** [comment]
Hiya! I'm a bit unsure what you mean as to instructions, unless you're referring to text-instructions for the people solving the captchas. 

If that's the case, this library supports passing in a field with instructions, something like
```js
Solver.imageCaptcha(img, {
    textinstructions: "Type each number in the image as it's spelled with the alphabet."
})```

this functionality can be found at the 2captcha api documentation (https://2captcha.com/2captcha-api), if this isn't what ya' mean though, feel free to elaborate more!

**Comment by Furry** [comment]
Closing this, feel free to reopen if you have more information ^^

**Comment by tacohitbox** [comment]
Oh yeah, I think it was this. Sorry for the lack of response until just now!!

**Comment by Furry** [comment]
> Oh yeah, I think it was this. Sorry for the lack of response until just now!!

All good, no worries!
