### ISSUE TITLE
TS declaration for 2Captcha API is not correct

### ISSUE THREAD

**Issue by sir-alex** [Furry/2captcha#22]
`   
min_len?: 0 | string;
max_len?: 0 | string;
`

is not correct as those 2 params are integers according to https://2captcha.com/2captcha-api

also it would be good to mention in documentation original 2Captcha API settings such as regsense, numeric etc as they are crucial and without right settings service can not work properly

**Comment by sir-alex** [comment]
I can make a PR if you wish

**Comment by Furry** [comment]
> ` min_len?: 0 | string; max_len?: 0 | string;`
> 
> is not correct as those 2 params are integers according to https://2captcha.com/2captcha-api
> 
> also it would be good to mention in documentation original 2Captcha API settings such as regsense, numeric etc as they are crucial and without right settings service can not work properly

This was a conscious choice, all the structures that extend BaseSolve are serialized into a QueryString parameter, so they're treated as a string once the http request is sent.

that being said, when people use the 2captcha api in reference to my library and that causes confusion, I can understand. If you want to make a PR that makes min_len & max_len a union of string & number i'll accept it!

**Comment by sir-alex** [comment]
PR is ready

**Comment by Furry** [comment]
> PR is ready

Merged it, thanks for the PR!
