### ISSUE TITLE
How do I use it with Puppeteer or Playwright?

### ISSUE THREAD

**Issue by jezsung** [Furry/2captcha#25]
I'm trying to bypass the v2Recaptcha but only calling `solver.recaptcha("6Ld2sf4SAAAAAKSgzs0Q13IZhY02Pyo31S2jgOB5", "https://patrickhlauke.github.io/recaptcha/")` doesn't seem working. It seems like I need to do something more to make it work but I have no clues. Can you please give me some instructions?

**Comment by Furry** [comment]
Apologize for the **extremely** long delay on this. The first parameter is the 'gkey', which is found within the website's html source. the second is the domain the captcha appears for the website you're trying to solve on.

There's instructions on how to find the needed data to use this library online ^^
