### ISSUE TITLE
Please add CHANGELOG

### ISSUE THREAD

**Issue by moltar** [Furry/2captcha#26]
It's not clear what changes are made, especially when major version bumps.

Usually, a major version bump signals breaking change.

I see there is v3 released, but I have no idea what needs to be changed to make it work.

Thanks!

**Comment by Furry** [comment]
I'm sorry, this is my first time with a relatively large library and I'm still new to the semantics of it.

I published 3.0 as a breaking change as that's when I added my affiliate url within the library, which gives me 10% of all captchas solved using this library. I figured it would be a bit scummy to do as a minor version, where people wouldn't have any idea about it, so I published it as a major version instead. It should act identical to the previous version, no changes needed!

As for a changelog, what might be the best way to go about implementing that? Just a MD file with each update note?

**Comment by moltar** [comment]
> As for a changelog, what might be the best way to go about implementing that?

I prefer to just use Conventional Commits and let the tools generate the `CHANGELOG.md` file.

But there are other similar approaches too.

But really, anything will work, even just having a small note for each version, where makes sense.

GitHub also supports releases and you can write notes there also.

**Comment by Furry** [comment]
Alright, thank you! I'll try to be much better about changelogs and versioning from now on! I appreciate the information!
