### ISSUE TITLE
Please expose custom error class

### ISSUE THREAD

**Issue by moltar** [Furry/2captcha#3]
Would be useful to have the error class exported: https://github.com/Furry/2captcha/blob/master/src/structs/2captchaError.ts

This way we can do:

```ts
if (err instanceof APIError && err.code === 1) {
  /// handle error
}
```

Thanks.

**Comment by moltar** [comment]
Right now, as a workaround, we can do:

```ts
import { APIError } from '2captcha/dist/structs/2captchaError'
```

**Comment by Furry** [comment]
Hiya, thanks for the issue! I added API error as a primary export from 'index' along with Solver.

a48b08e It's useable on the latest version of 2captcha from NPM, 2captcha@2.1.4

**Comment by moltar** [comment]
Thank you!
