### ISSUE TITLE
Google Captcha iFrame

### ISSUE THREAD

**Issue by JavedBoqo** [Furry/2captcha#34]
Hello,

I am getting token from  2Captcha but when i hit submit button then still Google Recaptcha iframe is showing.....
![Screenshot 2022-09-19 19 50 29](https://user-images.githubusercontent.com/683891/191046582-fea2ed53-e167-4e74-b0e8-612fcfdfa786.png)

**Comment by Furry** [comment]
2captcha's official site  provides documentation on how to inject the solution into the iframe. 
https://2captcha.com/2captcha-api#solving_recaptchav2_new:~:text=get%26id%3D2122988149-,reCAPTCHA%20V2,-reCAPTCHA%20V2%20also
