### ISSUE TITLE
Can make library for capsolver?

### ISSUE THREAD

**Issue by creppy1** [Furry/2captcha#37]
This service have the cheapest prices for captcha solving

**Comment by Furry** [comment]
Hiya there. I've already started this actually! I've been lacking in time to work on it. The existing library so far still had their old domain name 'captchaai', so I just went through and renamed it and republished to NPM.

https://www.npmjs.com/package/capsolver
https://github.com/furry/capsolver

There's going to be bugs as I just started work on that library and capsolver's api is a lot more involved than 2captchas. Feel free to give it a try and open an issue if there's anything wrong!
