### ISSUE TITLE
HELP!  How to pass the captcha back to Discord?

### ISSUE THREAD

**Issue by NotGoodCoding** [Furry/2captcha#38]
I receive the captcha response from 2captcha, that's all good.

But how does the captcha response gets passed back to Discord?

For example, when you send a message and an HCAPTCHA solving is required, 2captcha works perfectly fine and I receive the response back, but using DISCORD.JS, how do I pass it back to Discord???

THanks.

**Comment by Furry** [comment]
Are you working with Discord Self-Bots?

**Comment by NotGoodCoding** [comment]
I do.

I use the discord.js-selfbot-v13

**Comment by Furry** [comment]
Sadly, this isn't really related to what my repository is for, you'd be better off making an issue request to the selfbot github instead..
