### ISSUE TITLE
How do Solve Image captchas with the option Case sensitive?

### ISSUE THREAD

**Issue by mikows** [Furry/2captcha#48]
I need to solve image captchas that are case sensitive, and I could'nt find any options in the UserImageCaptchaExtra that corresponded to that.

**Comment by Furry** [comment]
For now, this is doable from the current build of the next branch that has many updates and options from 2captcha.

https://www.npmjs.com/package/2captcha/v/4.0.0-1
https://github.com/Furry/2captcha/commit/825fe927fcdf590cd6f689890499d8f96fc726fe
